%YAML 1.2
---
cpu: 2
disable_animation: false
exclude: '[./.*, ./__*]'
hardware: AMPERE_A6000
include: '[./*, main.py, requirements.txt, pkglist.txt, conda_pkglist.txt]'
log_level: INFO
memory: 30.0 # 25 uses 99% of memory so increased to 30.
