%YAML 1.2
---
cpu: 2
disable_animation: true
exclude: '[./.*, ./__*]'
hardware: AMPERE_A6000
include: '[./*, main.py, requirements.txt, pkglist.txt, conda_pkglist.txt]'
log_level: INFO
memory: 40
predict_data: '{"prompt": "The quick brown fox jumps over the lazy dog"}'