name: "Deploy Prebuilt"
on:
    repository_dispatch:
      types: [deploy-prebuilt]

env:
    NAME: ""
    API_KEY: ""
    HARDWARE: "TURING_5000"
    CPU: "2"
    MEMORY: "14.5"

# Event should have the following:
#   name: name of the deployment
#   api_key: cerebrium api key
#   hardware: hardware type
#   cpu: cpu
#   memory: memory
#   template_folder: folder where the template is located
#   hide_build_logs: true/false


jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Mask API-Key
        run: |
          API_KEY=$(jq -r '.inputs.api_key' $GITHUB_EVENT_PATH)
          echo ::add-mask::$API_KEY
          echo API_KEY=$API_KEY >> $GITHUB_ENV

      - name: Install Cerebrium
        run: pip install cerebrium

      - name: Cerebrium deploy
        # run: cerebrium deploy ${{env.NAME}} --api-key ${{env.API_KEY}} --hardware ${{env.HARDWARE}} --cpu ${{env.CPU}} --memory ${{env.MEMORY}}
        run: |
          export templatePath="$(pwd)/${{github.event.client_payload.template_folder}}"
          echo "Template Path: $templatePath"
          if [ -d $templatePath ]; then
            echo "Template Folder: ${{github.event.client_payload.template_folder}}"
            cd ./${{github.event.client_payload.template_folder}}
          else
            echo "Template Folder does not exist"
            exit 1
          fi

          echo "Current Directory: $(pwd)"
          echo "Found the following files:"
          ls ./
          if [ ${{github.event.client_payload.hide_build_logs}} == "true" ]; then
            echo "Hiding build logs"
            export buildParams="--hide-public-endpoint --hide-build-logs"
          else
            export buildParams="--hide-public-endpoint"
          fi

          cerebrium deploy ${{github.event.client_payload.name}} --api-key ${{env.API_KEY}} --hardware ${{github.event.client_payload.hardware}} --cpu ${{github.event.client_payload.cpu}} --memory ${{github.event.client_payload.memory}} $buildParams
