name: "Deploy Prebuilt"
on:
  workflow_dispatch:
    inputs:
      api_key:
        description: "API Key"
        type: string
        required: true

      template_folder:
        description: "Path to template folder in repo"
        type: string
        required: true

      name:
        description: "Name"
        type: string
        required: true

      hardware:
        description: "Hardware"
        type: choice
        required: false
        default: "TURING_5000"
        options:
          - "CPU"
          - "A10"
          - "TURING_4000"
          - "TURING_5000"
          - "AMPERE_A4000"
          - "AMPERE_A5000"
          - "AMPERE_A6000"
          - "AMPERE_A100"

      cpu:
        description: "Number of CPUs"
        type: string
        required: false
        default: ""

      memory:
        description: "Memory in GB"
        type: string
        required: false
        default: ""
      
      hide_build_logs:
        description: "Hide build logs"
        type: boolean
        required: false
        default: false

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

        # Set the working dir
        # working-directory: ${{github.event.inputs.template_folder}} ???

        # change dir into the provided template folder

      - name: Mask API-Key
        run: |
          API_KEY=$(yq -r '.inputs.api_key' $GITHUB_EVENT_PATH)
          echo ::add-mask::$API_KEY
          echo API_KEY=$API_KEY >> $GITHUB_ENV

      - name: Install Cerebrium
        run: pip install cerebrium

      - name: Cerebrium deploy
        run: |
          export templatePath="$(pwd)/${{github.event.inputs.template_folder}}"
          echo "Template Path: $templatePath"
          if [ -d $templatePath ]; then
            echo "Template Folder: ${{github.event.inputs.template_folder}}"
            cd ./${{github.event.inputs.template_folder}}
          else
            echo "Template Folder does not exist"
            exit 1
          fi

          echo "Current Directory: $(pwd)"
          echo "Found the following files:"
          ls ./

          export buildParams=" "
          if [ "${{github.event.inputs.disable_build_logs}}" == "true" ] || [ "${{github.event.inputs.disable_build_logs}}" == "True" ]; then
            echo "Hiding build logs"
            export buildParams="--disable_build_logs $buildParams"
          fi

          export CONFIG_FILE='./config.yaml'
          if [ -f $CONFIG_FILE ]; then
            echo "Config file $CONFIG_FILE exists"
            export buildParams="--config-file $CONFIG_FILE $buildParams"
          fi

          if [ ${{github.event.inputs.hardware}} ]; then
            echo "Hardware: ${{github.event.inputs.hardware}}"
            export buildParams="--hardware ${{github.event.inputs.hardware}} $buildParams"
          fi

          if [ ${{github.event.inputs.cpu}} ]; then
            echo "CPU: ${{github.event.inputs.cpu}}"
            export buildParams="--cpu ${{github.event.inputs.cpu}} $buildParams"
          fi

          if [ ${{github.event.inputs.memory}} ]; then
            echo "Memory: ${{github.event.inputs.memory}}"
            export buildParams="--memory ${{github.event.inputs.memory}} $buildParams"
          fi

          if [ ${{github.event.inputs.name}} ]; then
            echo "Name: ${{github.event.inputs.name}}"
            export buildParams="${{github.event.inputs.name}} $buildParams"
          fi

          echo ""
          echo "-----------------------------------------"
          echo "Deploying to Cerebrium..."

          echo "using params:  $buildParams "
          cerebrium deploy --api-key '${{env.API_KEY}}' $buildParams --hide-public-endpoint
  