name: "Deploy Prebuilt from POST"
on:
  repository_dispatch:
    types: [deploy-prebuilt]

# Event should have the following:
#   name: name of the deployment
#   api_key: cerebrium api key
#   hardware: hardware type
#   cpu: cpu
#   memory: memory
#   template_folder: folder where the template is located
#   hide_build_logs: true/false

# EXAMPLE REQUEST:
#   curl -L \
#   -X POST \
#   -H "Accept: application/vnd.github+json" \
#   -H "Authorization: Bearer <YOUR-TOKEN>" \
#   -H "X-GitHub-Api-Version: 2022-11-28" \
#   https://api.github.com/repos/CerebriumAI/cerebrium-prebuilts/dispatches \
#   -d '{"event_type":"deploy-prebuilt","client_payload":{"name":"Test", "api_key"hardware":"AMPERE_A4000", "cpu":"2", "memory":"14.5", "template_folder":"dreambooth", "hide_build_logs":"true"}}'

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Mask API-Key
        run: |
          API_KEY=$(yq -r '.client_payload.api_key' $GITHUB_EVENT_PATH)
          echo ::add-mask::$API_KEY
          echo API_KEY=$API_KEY >> $GITHUB_ENV

      - name: Install Cerebrium
        run: pip install cerebrium

      - name: Cerebrium deploy
        # run: cerebrium deploy --name ${{env.NAME}} --api-key ${{env.API_KEY}} --gpu ${{env.gpu}} --cpu ${{env.CPU}} --memory ${{env.MEMORY}}
        run: |
            echo "Starting Deployment with Cerebrium!"
            if [ "${{github.event.client_payload.environment}}" == "dev" ]; then
                echo "Deploying to dev environment"
                export ENV=dev
            fi

            export templatePath="$(pwd)/${{github.event.client_payload.template_folder}}"
            echo "Template Path: $templatePath"
            if [ -d $templatePath ]; then
                echo "Template Folder: ${{github.event.client_payload.template_folder}}"
                cd ./${{github.event.client_payload.template_folder}}
            else
                echo "Template Folder does not exist"
                exit 1
            fi

            echo "Current Directory: $(pwd)"
            echo "Found the following files:"
            ls ./
            
            echo ""
            export buildParams=" "
            if [ "${{github.event.client_payload.disable_build_logs}}" == "true" ] || [ "${{github.event.client_payload.disable_build_logs}}" == "True" ]; then
                echo "Hiding build logs"
                export buildParams="--disable_build_logs $buildParams"
            fi

            export CONFIG_FILE='./config.yaml'
            if [ -f $CONFIG_FILE ]; then
                echo "Config file $CONFIG_FILE exists"
                export buildParams="--config-file $CONFIG_FILE $buildParams"
            fi

            if [ "${{github.event.client_payload.hardware}}" != "" ]; then
                echo "GPU: ${{github.event.client_payload.hardware}}"
                export buildParams="--gpu ${{github.event.client_payload.hardware}} $buildParams"
            fi

            if [ "${{github.event.client_payload.cpu}}" != "" ]; then
                echo "CPU: ${{github.event.client_payload.cpu}}"
                export buildParams="--cpu ${{github.event.client_payload.cpu}} $buildParams"
            fi

            if [ "${{github.event.client_payload.memory}}" != "" ]; then
                echo "Memory: ${{github.event.client_payload.memory}}"
                export buildParams="--memory ${{github.event.client_payload.memory}} $buildParams"
            fi

            if [ "${{github.event.client_payload.name}}" != "" ]; then
                echo "Deployment name: ${{github.event.client_payload.name}}"
                export buildParams="--name ${{github.event.client_payload.name}} $buildParams"
            fi

            echo ""
            echo "-----------------------------------------"
            echo "Deploying to Cerebrium..."

            echo "params:  $buildParams "
            yes | cerebrium deploy --api-key ${{env.API_KEY}} --hide-public-endpoint --disable-predict --disable-syntax-check -q $buildParams 
      - name: Notify Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: job,repo
          custom_payload: |
            {
              channel: '#crash_notifications',
              attachments: [{
                color: "${{ job.status }}",
                title: `Prebuilt model ${{github.event.client_payload.name}} deploy failed`,
                text: `Your Github Actions job for a pre-built model failed.`,
                fields: [{
                  title: 'Action URL',
                  value: `${{ github.event.pull_request.html_url || github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
                }]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CRASH_SLACK_WEBHOOK_URL }}
          
