name: "Deploy Prebuilt from POST"
on:
  repository_dispatch:
    types: [deploy-prebuilt]

env:
  NAME: ""
  API_KEY: ""
  HARDWARE: "TURING_5000"
  CPU: "2"
  MEMORY: "14.5"

# Event should have the following:
#   name: name of the deployment
#   api_key: cerebrium api key
#   hardware: hardware type
#   cpu: cpu
#   memory: memory
#   template_folder: folder where the template is located
#   hide_build_logs: true/false

# EXAMPLE REQUEST:
#   curl -L \
#   -X POST \
#   -H "Accept: application/vnd.github+json" \
#   -H "Authorization: Bearer <YOUR-TOKEN>" \
#   -H "X-GitHub-Api-Version: 2022-11-28" \
#   https://api.github.com/repos/CerebriumAI/cerebrium-prebuilts/dispatches \
#   -d '{"event_type":"deploy-prebuilt","client_payload":{"name":"Test", "api_key"hardware":"AMPERE_A4000", "cpu":"2", "memory":"14.5", "template_folder":"dreambooth", "hide_build_logs":"true"}}'

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Mask API-Key
        run: |
          API_KEY=${{github.event.client_payload.api_key}}
          echo ::add-mask::$API_KEY
          echo API_KEY=$API_KEY >> $GITHUB_ENV

      - name: Install Cerebrium
        run: pip install cerebrium

      - name: Cerebrium deploy
        # run: cerebrium deploy ${{env.NAME}} --api-key ${{env.API_KEY}} --hardware ${{env.HARDWARE}} --cpu ${{env.CPU}} --memory ${{env.MEMORY}}
        run: |
          export templatePath="$(pwd)/${{github.event.client_payload.template_folder}}"
          echo "Template Path: $templatePath"
          if [ -d $templatePath ]; then
            echo "Template Folder: ${{github.event.client_payload.template_folder}}"
            cd ./${{github.event.client_payload.template_folder}}
          else
            echo "Template Folder does not exist"
            exit 1
          fi

          echo "Current Directory: $(pwd)"
          echo "Found the following files:"
          ls ./
          
          echo ""

          if [ "${{github.event.client_payload.disable_build_logs}}" = "true" ] || [ "${{github.event.client_payload.disable_build_logs}}" = "True" ]; then
            echo "Hiding build logs"
            export buildParams="--hide-public-endpoint --disable_build_logs"
          else
            export buildParams="--hide-public-endpoint"
          fi

          echo ""
          echo "-----------------------------------------"
          echo "Deploying to Cerebrium..."

          echo "params:  ${{github.event.client_payload.name}} --api-key ${{env.API_KEY}} --hardware ${{github.event.client_payload.hardware}} --cpu ${{github.event.client_payload.cpu}} --memory ${{github.event.client_payload.memory}} $buildParams "

          cerebrium deploy ${{github.event.client_payload.name}} --api-key ${{env.API_KEY}} --hardware ${{github.event.client_payload.hardware}} --cpu ${{github.event.client_payload.cpu}} --memory ${{github.event.client_payload.memory}} $buildParams

          