name: "Deploy Prebuilt"
on:
  workflow_dispatch:
    inputs:
      api_key:
        description: "API Key"
        type: string
        required: true

      template_folder:
        description: "Path to template folder in repo"
        type: string
        required: true

      name:
        description: "Name"
        type: string
        required: true

      hardware:
        description: "Hardware"
        type: choice
        required: false
        default: "TURING_5000"
        options:
          - "None"
          - "CPU"
          - "A10"
          - "TURING_4000"
          - "TURING_5000"
          - "AMPERE_A4000"
          - "AMPERE_A5000"
          - "AMPERE_A6000"
          - "AMPERE_A100"

      cpu:
        description: "Number of CPUs"
        type: string
        required: false
        default: "2"

      memory:
        description: "Memory in GB"
        type: string
        required: false
        default: "14.5"
      
      hide_build_logs:
        description: "Hide build logs"
        type: boolean
        required: false
        default: false

env: 
  NAME: ${{github.event.inputs.name}}
  API_KEY: ${{github.event.inputs.api_key}}
  HARDWARE: ${{github.event.inputs.hardware}}
  CPU: ${{github.event.inputs.cpu}}
  MEMORY: ${{github.event.inputs.memory}}
  CONFIG_FILE: $(pwd)/${{github.event.inputs.template_folder}}/config.yaml

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    env:
      NAME: ${{github.event.inputs.name}}
      API_KEY: ${{github.event.inputs.api_key}}
      HARDWARE: ${{github.event.inputs.hardware}}
      CPU: ${{github.event.inputs.cpu}}
      MEMORY: ${{github.event.inputs.memory}}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

        # Set the working dir
        # working-directory: ${{github.event.inputs.template_folder}} ???

        # change dir into the provided template folder

      - name: Mask API-Key
        run: |
          API_KEY=$(yq -r '.inputs.api_key' $GITHUB_EVENT_PATH)
          echo ::add-mask::$API_KEY
          echo API_KEY=$API_KEY >> $GITHUB_ENV

      - name: Install Cerebrium
        run: pip install cerebrium

      - name: Cerebrium deploy
        # run: cerebrium deploy ${{env.NAME}} --api-key ${{env.API_KEY}} --hardware ${{env.HARDWARE}} --cpu ${{env.CPU}} --memory ${{env.MEMORY}}
        run: |
          export templatePath="$(pwd)/${{github.event.inputs.template_folder}}"
          echo "Template Path: $templatePath"
          if [ -d $templatePath ]; then
            echo "Template Folder: ${{github.event.inputs.template_folder}}"
            cd ./${{github.event.inputs.template_folder}}
          else
            echo "Template Folder does not exist"
            exit 1
          fi

          echo "Current Directory: $(pwd)"
          echo "Found the following files:"
          ls ./

          echo ""

          export buildParams="--hide-public-endpoint"

          if [ ${{github.event.inputs.hide_build_logs}} == "true" ]; then
            echo "Hiding build logs"
            export buildParams="--hide-public-endpoint $buildParams"
          fi

          echo "CONFIG_FILE: $CONFIG_FILE"
          if [ -f $CONFIG_FILE ]; then
            echo "Config file $CONFIG_FILE exists"
            export buildParams="--config-file $CONFIG_FILE $buildParams"

          cerebrium deploy ${{github.event.inputs.name}} --api-key ${{env.API_KEY}} --hardware ${{github.event.inputs.hardware}} --cpu ${{github.event.inputs.cpu}} --memory ${{github.event.inputs.memory}} $buildParams
  